# Thank you for using SimpleBroadcast
# Version: 1.0
# Made by: Evildude221
# Requested by: GetSwated

ShowServerName: true
ServerName: '&f[&aBroadcast&f]'
PlayerColor: '&7'
MessageColor: '&f'
ErrorMessage: '&cYou need a message to broadcast silly!'