name: SimpleBroadcast
main: me.cgfx360.simplebroadcast.Main
version: 1.4
description: >
             Simply broadcast's a message
commands:
  broadcast:
    description: Main command
    aliases: [bc, say, ebc, ebroadcast, bcast, ebcast, shout, eshout]
    permission: sb.use
    permission-message: §cYou don't have permission
permissions:
  sb.use:
    default: op

    